const playerData  = [
  {
    player_number: 1,
    country: "Mexico",
    position: "GK",
    player_name: "Raúl Rangel",
    is_captain: "No",
    dob_age: "February 25, 2000 (aged 26)",
    caps: 14,
    goals: 0,
    club: "Guadalajara",
    club_location: "Mexico"
  },
  {
    player_number: 2,
    country: "Mexico",
    position: "DF",
    player_name: "Jorge Sánchez",
    is_captain: "No",
    dob_age: "December 10, 1997 (aged 28)",
    caps: 59,
    goals: 3,
    club: "PAOK",
    club_location: "Greece"
  },
  {
    player_number: 3,
    country: "Mexico",
    position: "DF",
    player_name: "César Montes",
    is_captain: "No",
    dob_age: "February 24, 1997 (aged 29)",
    caps: 67,
    goals: 4,
    club: "Lokomotiv Moscow",
    club_location: "Russia"
  },
  {
    player_number: 4,
    country: "Mexico",
    position: "DF",
    player_name: "Edson Álvarez",
    is_captain: "Yes",
    dob_age: "October 24, 1997 (aged 28)",
    caps: 98,
    goals: 7,
    club: "Fenerbahçe",
    club_location: "Türkiye"
  },
  {
    player_number: 5,
    country: "Mexico",
    position: "DF",
    player_name: "Johan Vásquez",
    is_captain: "No",
    dob_age: "October 22, 1998 (aged 27)",
    caps: 46,
    goals: 3,
    club: "Genoa",
    club_location: "Italy"
  },
  {
    player_number: 6,
    country: "Mexico",
    position: "MF",
    player_name: "Érik Lira",
    is_captain: "No",
    dob_age: "May 8, 2000 (aged 26)",
    caps: 25,
    goals: 0,
    club: "Cruz Azul",
    club_location: "Mexico"
  },
  {
    player_number: 7,
    country: "Mexico",
    position: "MF",
    player_name: "Luis Romo",
    is_captain: "No",
    dob_age: "June 5, 1995 (aged 31)",
    caps: 63,
    goals: 4,
    club: "Guadalajara",
    club_location: "Mexico"
  },
  {
    player_number: 8,
    country: "Mexico",
    position: "MF",
    player_name: "Álvaro Fidalgo",
    is_captain: "No",
    dob_age: "April 9, 1997 (aged 29)",
    caps: 4,
    goals: 0,
    club: "Real Betis",
    club_location: "Spain"
  },
  {
    player_number: 9,
    country: "Mexico",
    position: "FW",
    player_name: "Raúl Jiménez",
    is_captain: "No",
    dob_age: "May 5, 1991 (aged 35)",
    caps: 124,
    goals: 45,
    club: "Fulham",
    club_location: "England"
  },
  {
    player_number: 10,
    country: "Mexico",
    position: "FW",
    player_name: "Alexis Vega",
    is_captain: "No",
    dob_age: "November 25, 1997 (aged 28)",
    caps: 52,
    goals: 7,
    club: "Toluca",
    club_location: "Mexico"
  },
  {
    player_number: 11,
    country: "Mexico",
    position: "FW",
    player_name: "Santiago Giménez",
    is_captain: "No",
    dob_age: "April 18, 2001 (aged 25)",
    caps: 47,
    goals: 6,
    club: "AC Milan",
    club_location: "Italy"
  },
  {
    player_number: 12,
    country: "Mexico",
    position: "GK",
    player_name: "Carlos Acevedo",
    is_captain: "No",
    dob_age: "April 19, 1996 (aged 30)",
    caps: 7,
    goals: 0,
    club: "Santos Laguna",
    club_location: "Mexico"
  },
  {
    player_number: 13,
    country: "Mexico",
    position: "GK",
    player_name: "Guillermo Ochoa",
    is_captain: "No",
    dob_age: "July 13, 1985 (aged 40)",
    caps: 152,
    goals: 0,
    club: "AEL Limassol",
    club_location: "Greece"
  },
  {
    player_number: 14,
    country: "Mexico",
    position: "FW",
    player_name: "Armando González",
    is_captain: "No",
    dob_age: "April 20, 2003 (aged 23)",
    caps: 7,
    goals: 1,
    club: "Guadalajara",
    club_location: "Mexico"
  },
  {
    player_number: 15,
    country: "Mexico",
    position: "DF",
    player_name: "Israel Reyes",
    is_captain: "No",
    dob_age: "May 23, 2000 (aged 26)",
    caps: 34,
    goals: 2,
    club: "América",
    club_location: "Mexico"
  },
  {
    player_number: 16,
    country: "Mexico",
    position: "FW",
    player_name: "Julián Quiñones",
    is_captain: "No",
    dob_age: "March 24, 1997 (aged 29)",
    caps: 22,
    goals: 2,
    club: "Al-Qadsiah",
    club_location: "Saudi Arabia"
  },
  {
    player_number: 17,
    country: "Mexico",
    position: "MF",
    player_name: "Orbelín Pineda",
    is_captain: "No",
    dob_age: "March 24, 1996 (aged 30)",
    caps: 92,
    goals: 12,
    club: "AEK Athens",
    club_location: "Greece"
  },
  {
    player_number: 18,
    country: "Mexico",
    position: "MF",
    player_name: "Obed Vargas",
    is_captain: "No",
    dob_age: "August 5, 2005 (aged 20)",
    caps: 6,
    goals: 0,
    club: "Atlético Madrid",
    club_location: "Spain"
  },
  {
    player_number: 19,
    country: "Mexico",
    position: "MF",
    player_name: "Gilberto Mora",
    is_captain: "No",
    dob_age: "October 14, 2008 (aged 17)",
    caps: 8,
    goals: 0,
    club: "Tijuana",
    club_location: "Mexico"
  },
  {
    player_number: 20,
    country: "Mexico",
    position: "DF",
    player_name: "Mateo Chávez",
    is_captain: "No",
    dob_age: "May 12, 2004 (aged 22)",
    caps: 10,
    goals: 0,
    club: "AZ",
    club_location: "Netherlands"
  },
  {
    player_number: 21,
    country: "Mexico",
    position: "FW",
    player_name: "César Huerta",
    is_captain: "No",
    dob_age: "December 3, 2000 (aged 25)",
    caps: 26,
    goals: 3,
    club: "Anderlecht",
    club_location: "Belgium"
  },
  {
    player_number: 22,
    country: "Mexico",
    position: "FW",
    player_name: "Guillermo Martínez",
    is_captain: "No",
    dob_age: "March 15, 1995 (aged 31)",
    caps: 12,
    goals: 3,
    club: "Pumas",
    club_location: "Mexico"
  },
  {
    player_number: 23,
    country: "Mexico",
    position: "DF",
    player_name: "Jesús Gallardo",
    is_captain: "No",
    dob_age: "August 15, 1994 (aged 31)",
    caps: 121,
    goals: 3,
    club: "Toluca",
    club_location: "Mexico"
  },
  {
    player_number: 24,
    country: "Mexico",
    position: "MF",
    player_name: "Luis Chávez",
    is_captain: "No",
    dob_age: "January 15, 1996 (aged 30)",
    caps: 45,
    goals: 5,
    club: "Dynamo Moscow",
    club_location: "Russia"
  },
  {
    player_number: 25,
    country: "Mexico",
    position: "FW",
    player_name: "Roberto Alvarado",
    is_captain: "No",
    dob_age: "September 7, 1998 (aged 27)",
    caps: 67,
    goals: 5,
    club: "Guadalajara",
    club_location: "Mexico"
  },
  {
    player_number: 26,
    country: "Mexico",
    position: "MF",
    player_name: "Brian Gutiérrez",
    is_captain: "No",
    dob_age: "June 17, 2003 (aged 22)",
    caps: 7,
    goals: 2,
    club: "Guadalajara",
    club_location: "Mexico"
  },
  {
    player_number: "1",
    country: "Bosnia & Herzegovina",
    position: "GK",
    player_name: "Nikola Vasilj",
    is_captain: "No",
   dob_age: "December 2, 1995 (aged 30)",
    caps: "26",
    goals: "0",
    club: "FC St. Pauli",
    club_location: "Germany"
  },
  {
    player_number: "2",
    country: "Bosnia & Herzegovina",
    position: "DF",
    player_name: "Nihad Mujakić",
    is_captain: "No",
   dob_age: "April 15, 1998 (aged 28)",
    caps: "12",
    goals: "1",
    club: "Gaziantep",
    club_location: "Türkiye"
  },
  {
    player_number: "3",
    country: "Bosnia & Herzegovina",
    position: "DF",
    player_name: "Dennis Hadžikadunić",
    is_captain: "No",
    dob_age: "July 9, 1998 (aged 27)",
    caps: "32",
    goals: "0",
    club: "Sampdoria",
    club_location: "Italy"
  },
  {
   player_number: "4",
    country: "Bosnia & Herzegovina",
    position: "DF",
    player_name: "Tarik Muharemović",
    is_captain: "No",
    dob_age: "February 28, 2003 (aged 23)",
    caps: "14",
    goals: "1",
    club: "Sassuolo",
    club_location: "Italy"
  },
  {
   player_number: "5",
    country: "Bosnia & Herzegovina",
    position: "DF",
    player_name: "Sead Kolašinac",
    is_captain: "No",
   dob_age: "June 20, 1993 (aged 32)",
    caps: "65",
    goals: "0",
    club: "Atalanta",
    club_location: "Italy"
  },
  {
   player_number: "6",
    country: "Bosnia & Herzegovina",
    position: "MF",
    player_name: "Benjamin Tahirović",
    is_captain: "No",
   dob_age: "March 3, 2003 (aged 23)",
    caps: "28",
    goals: "2",
    club: "Brøndby",
    club_location: "Denmark"
  },
  {
   player_number: "7",
    country: "Bosnia & Herzegovina",
    position: "DF",
    player_name: "Amar Dedić",
    is_captain: "No",
   dob_age: "August 18, 2002 (aged 23)",
    caps: "28",
    goals: "1",
    club: "Benfica",
    club_location: "Portugal"
  },
  {
   player_number: "8",
    country: "Bosnia & Herzegovina",
    position: "MF",
    player_name: "Armin Gigović",
    is_captain: "No",
   dob_age: "April 6, 2002 (aged 24)",
    caps: "20",
    goals: "1",
    club: "Young Boys",
    club_location: "Switzerland"
  },
  {
   player_number: "9",
    country: "Bosnia & Herzegovina",
    position: "FW",
    player_name: "Samed Baždar",
    is_captain: "No",
   dob_age: "January 31, 2004 (aged 22)",
    caps: "13",
    goals: "1",
    club: "Jagiellonia Białystok",
    club_location: "Poland"
  },
  {
   player_number: "10",
    country: "Bosnia & Herzegovina",
    position: "FW",
    player_name: "Ermedin Demirović",
    is_captain: "No",
   dob_age: "March 25, 1998 (aged 28)",
    caps: "40",
    goals: "4",
    club: "VfB Stuttgart",
    club_location: "Germany"
  },
  {
   player_number: "11",
    country: "Bosnia & Herzegovina",
    position: "FW",
    player_name: "Edin Džeko",
    is_captain: "Yes",
   dob_age: "March 17, 1986 (aged 40)",
    caps: "148",
    goals: "73",
    club: "Schalke 04",
    club_location: "Germany"
  },
  {
   player_number: "12",
    country: "Bosnia & Herzegovina",
    position: "GK",
    player_name: "Mladen Jurkas",
    is_captain: "No",
   dob_age: "October 7, 2007 (aged 18)",
    caps: "0",
    goals: "0",
    club: "Borac Banja Luka",
    club_location: "Bosnia & Herzegovina"
  },
  {
   player_number: "13",
    country: "Bosnia & Herzegovina",
    position: "MF",
    player_name: "Ivan Bašić",
    is_captain: "No",
   dob_age: "April 30, 2002 (aged 24)",
    caps: "17",
    goals: "0",
    club: "Astana",
    club_location: "Kazakhstan"
  },
  {
   player_number: "14",
    country: "Bosnia & Herzegovina",
    position: "MF",
    player_name: "Ivan Šunjić",
    is_captain: "No",
   dob_age: "October 9, 1996 (aged 29)",
    caps: "11",
    goals: "0",
    club: "Pafos",
    club_location: "Cyprus"
  },
  {
   player_number: "15",
    country: "Bosnia & Herzegovina",
    position: "MF",
    player_name: "Amar Memić",
    is_captain: "No",
   dob_age: "January 20, 2001 (aged 25)",
    caps: "13",
    goals: "1",
    club: "Viktoria Plzeň",
    club_location: "Czechia"
  },
  {
   player_number: "16",
    country: "Bosnia & Herzegovina",
    position: "MF",
    player_name: "Amir Hadžiahmetović",
    is_captain: "No",
   dob_age: "March 8, 1997 (aged 29)",
    caps: "36",
    goals: "0",
    club: "Hull City",
    club_location: "England"
  },
  {
   player_number: "17",
    country: "Bosnia & Herzegovina",
    position: "MF",
    player_name: "Dženis Burnić",
    is_captain: "No",
   dob_age: "May 22, 1998 (aged 28)",
    caps: "20",
    goals: "0",
    club: "Karlsruher SC",
    club_location: "Germany"
  },
  {
   player_number: "18",
    country: "Bosnia & Herzegovina",
    position: "DF",
    player_name: "Nikola Katić",
    is_captain: "No",
   dob_age: "October 10, 1996 (aged 29)",
    caps: "17",
    goals: "2",
    club: "Schalke 04",
    club_location: "Germany"
  },
  {
   player_number: "19",
    country: "Bosnia & Herzegovina",
    position: "FW",
    player_name: "Kerim Alajbegović",
    is_captain: "No",
   dob_age: "September 21, 2007 (aged 18)",
    caps: "10",
    goals: "1",
    club: "Red Bull Salzburg",
    club_location: "Austria"
  },
  {
   player_number: "20",
    country: "Bosnia & Herzegovina",
    position: "FW",
    player_name: "Esmir Bajraktarević",
    is_captain: "No",
   dob_age: "March 10, 2005 (aged 21)",
    caps: "16",
    goals: "1",
    club: "PSV Eindhoven",
    club_location: "Netherlands"
  },
  {
   player_number: "21",
    country: "Bosnia & Herzegovina",
    position: "DF",
    player_name: "Stjepan Radeljić",
    is_captain: "No",
   dob_age: "September 5, 1997 (aged 28)",
    caps: "5",
    goals: "0",
    club: "Rijeka",
    club_location: "Croatia"
  },
  {
   player_number: "22",
    country: "Bosnia & Herzegovina",
    position: "GK",
    player_name: "Martin Zlomislić",
    is_captain: "No",
   dob_age: "August 16, 1998 (aged 27)",
    caps: "3",
    goals: "0",
    club: "Rijeka",
    club_location: "Croatia"
  },
  {
   player_number: "23",
    country: "Bosnia & Herzegovina",
    position: "FW",
    player_name: "Haris Tabaković",
    is_captain: "No",
   dob_age: "June 20, 1994 (aged 31)",
    caps: "10",
    goals: "4",
    club: "Borussia Mönchengladbach",
    club_location: "Germany"
  },
  {
   player_number: "24",
    country: "Bosnia & Herzegovina",
    position: "DF",
    player_name: "Arjan Malić",
    is_captain: "No",
   dob_age: "August 28, 2005 (aged 20)",
    caps: "8",
    goals: "0",
    club: "Sturm Graz",
    club_location: "Austria"
  },
  {
   player_number: "25",
    country: "Bosnia & Herzegovina",
    position: "FW",
    player_name: "Jovo Lukić",
    is_captain: "No",
   dob_age: "November 28, 1998 (aged 27)",
    caps: "3",
    goals: "0",
    club: "Universitatea Cluj",
    club_location: "Romania"
  },
  {
   player_number: "26",
    country: "Bosnia & Herzegovina",
    position: "MF",
    player_name: "Ermin Mahmić",
    is_captain: "No",
   dob_age: "March 14, 2005 (aged 21)",
    caps: "2",
    goals: "0",
    club: "Slovan Liberec",
    club_location: "Czechia"
  },
  {
    player_number: "1",
    country: "South Korea",
    position: "GK",
    player_name: "Kim Seung-gyu",
    is_captain: "No",
   dob_age: "September 30, 1990 (aged 35)",
    caps: "87",
    goals: "0",
    club: "FC Tokyo",
    club_location: "Japan"
  },
  {
    player_number: "2",
    country: "South Korea",
    position: "DF",
    player_name: "Lee Han-beom",
    is_captain: "No",
   dob_age: "June 17, 2002 (aged 23)",
    caps: "8",
    goals: "0",
    club: "Midtjylland",
    club_location: "Denmark"
  },
  {
    player_number: "3",
    country: "South Korea",
    position: "MF",
    player_name: "Lee Gi-hyuk",
    is_captain: "No",
   dob_age: "July 7, 2000 (aged 25)",
    caps: "3",
    goals: "0",
    club: "Gangwon FC",
    club_location: "South Korea"
  },
  {
    player_number: "4",
    country: "South Korea",
    position: "DF",
    player_name: "Kim Min-jae",
    is_captain: "No",
   dob_age: "November 15, 1996 (aged 29)",
    caps: "79",
    goals: "4",
    club: "Bayern Munich",
    club_location: "Germany"
  },
  {
    player_number: "5",
    country: "South Korea",
    position: "DF",
    player_name: "Kim Tae-hyeon",
    is_captain: "No",
   dob_age: "September 17, 2000 (aged 25)",
    caps: "7",
    goals: "0",
    club: "Kashima Antlers",
    club_location: "Japan"
  },
  {
    player_number: "6",
    country: "South Korea",
    position: "MF",
    player_name: "Hwang In-beom",
    is_captain: "No",
   dob_age: "September 20, 1996 (aged 29)",
    caps: "73",
    goals: "6",
    club: "Feyenoord",
    club_location: "Netherlands"
  },
  {
    player_number: "7",
    country: "South Korea",
    position: "FW",
    player_name: "Son Heung-min",
    is_captain: "Yes",
   dob_age: "July 8, 1992 (aged 33)",
    caps: "144",
    goals: "56",
    club: "Los Angeles FC",
    club_location: "United States"
  },
  {
    player_number: "8",
    country: "South Korea",
    position: "MF",
    player_name: "Paik Seung-ho",
    is_captain: "No",
   dob_age: "March 17, 1997 (aged 29)",
    caps: "27",
    goals: "3",
    club: "Birmingham City",
    club_location: "England"
  },
  {
    player_number: "9",
    country: "South Korea",
    position: "FW",
    player_name: "Cho Gue-sung",
    is_captain: "No",
   dob_age: "January 25, 1998 (aged 28)",
    caps: "44",
    goals: "12",
    club: "Midtjylland",
    club_location: "Denmark"
  },
  {
    player_number: "10",
    country: "South Korea",
    position: "MF",
    player_name: "Lee Jae-sung",
    is_captain: "No",
   dob_age: "August 10, 1992 (aged 33)",
    caps: "105",
    goals: "15",
    club: "Mainz 05",
    club_location: "Germany"
  },
  {
    player_number: "11",
    country: "South Korea",
    position: "MF",
    player_name: "Hwang Hee-chan",
    is_captain: "No",
   dob_age: "January 26, 1996 (aged 30)",
    caps: "79",
    goals: "17",
    club: "Wolverhampton Wanderers",
    club_location: "England"
  },
  {
    player_number: "12",
    country: "South Korea",
    position: "GK",
    player_name: "Song Bum-keun",
    is_captain: "No",
   dob_age: "October 15, 1997 (aged 28)",
    caps: "3",
    goals: "0",
    club: "Jeonbuk Hyundai Motors",
    club_location: "South Korea"
  },
  {
    player_number: "13",
    country: "South Korea",
    position: "DF",
    player_name: "Lee Tae-seok",
    is_captain: "No",
   dob_age: "July 28, 2002 (aged 23)",
    caps: "15",
    goals: "1",
    club: "Austria Wien",
    club_location: "Austria"
  },
  {
    player_number: "14",
    country: "South Korea",
    position: "DF",
    player_name: "Cho Wi-je",
    is_captain: "No",
   dob_age: "August 25, 2001 (aged 24)",
    caps: "1",
    goals: "0",
    club: "Jeonbuk Hyundai Motors",
    club_location: "South Korea"
  },
  {
    player_number: "15",
    country: "South Korea",
    position: "DF",
    player_name: "Kim Moon-hwan",
    is_captain: "No",
   dob_age: "August 1, 1995 (aged 30)",
    caps: "35",
    goals: "0",
    club: "Daejeon Hana Citizen",
    club_location: "South Korea"
  },
  {
    player_number: "16",
    country: "South Korea",
    position: "DF",
    player_name: "Park Jin-seob",
    is_captain: "No",
   dob_age: "October 23, 1995 (aged 30)",
    caps: "14",
    goals: "1",
    club: "Zhejiang",
    club_location: "China"
  },
  {
    player_number: "17",
    country: "South Korea",
    position: "MF",
    player_name: "Bae Jun-ho",
    is_captain: "No",
   dob_age: "August 21, 2003 (aged 22)",
    caps: "13",
    goals: "2",
    club: "Stoke City",
    club_location: "England"
  },
  {
    player_number: "18",
    country: "South Korea",
    position: "FW",
    player_name: "Oh Hyeon-gyu",
    is_captain: "No",
   dob_age: "April 12, 2001 (aged 25)",
    caps: "27",
    goals: "6",
    club: "Beşiktaş",
    club_location: "Türkiye"
  },
  {
    player_number: "19",
    country: "South Korea",
    position: "MF",
    player_name: "Lee Kang-in",
    is_captain: "No",
   dob_age: "February 19, 2001 (aged 25)",
    caps: "47",
    goals: "11",
    club: "Paris Saint-Germain",
    club_location: "France"
  },
  {
    player_number: "20",
    country: "South Korea",
    position: "MF",
    player_name: "Yang Hyun-jun",
    is_captain: "No",
   dob_age: "May 25, 2002 (aged 24)",
    caps: "9",
    goals: "0",
    club: "Celtic",
    club_location: "Scotland"
  },
  {
    player_number: "21",
    country: "South Korea",
    position: "GK",
    player_name: "Jo Hyeon-woo",
    is_captain: "No",
   dob_age: "September 25, 1991 (aged 34)",
    caps: "48",
    goals: "0",
    club: "Ulsan HD",
    club_location: "South Korea"
  },
  {
    player_number: "22",
    country: "South Korea",
    position: "DF",
    player_name: "Seol Young-woo",
    is_captain: "No",
   dob_age: "December 5, 1998 (aged 27)",
    caps: "34",
    goals: "0",
    club: "Red Star Belgrade",
    club_location: "Serbia"
  },
  {
    player_number: "23",
    country: "South Korea",
    position: "DF",
    player_name: "Jens Castrop",
    is_captain: "No",
   dob_age: "July 29, 2003 (aged 22)",
    caps: "7",
    goals: "0",
    club: "Borussia Mönchengladbach",
    club_location: "Germany"
  },
  {
    player_number: "24",
    country: "South Korea",
    position: "MF",
    player_name: "Kim Jin-gyu",
    is_captain: "No",
   dob_age: "February 24, 1997 (aged 29)",
    caps: "22",
    goals: "3",
    club: "Jeonbuk Hyundai Motors",
    club_location: "South Korea"
  },
  {
    player_number: "25",
    country: "South Korea",
    position: "MF",
    player_name: "Eom Ji-sung",
    is_captain: "No",
   dob_age: "May 9, 2002 (aged 24)",
    caps: "9",
    goals: "2",
    club: "Swansea City",
    club_location: "Wales"
  },
  {
    player_number: "26",
    country: "South Korea",
    position: "MF",
    player_name: "Lee Dong-gyeong",
    is_captain: "No",
    dob_age: "September 20, 1997 (aged 28)",
    caps: "18",
    goals: "4",
    club: "Ulsan HD",
    club_location: "South Korea"
  },
  {
    player_number: "1",
    position: "GK",
    country: "South Africa",
    player_name: "Ronwen Williams",
    is_captain: "Yes",
    dob_age: "January 21, 1992 (aged 34)",
    caps: "62",
    goals: "0",
    club: "Mamelodi Sundowns",
    club_location: "South Africa"
  },
  {
    player_number: "2",
    position: "DF",
    country: "South Africa",
    player_name: "Thabang Matuludi",
    is_captain: "No",
    dob_age: "January 14, 1999 (aged 27)",
    caps: "3",
    goals: "0",
    club: "Polokwane City",
    club_location: "South Africa"
  },
  {
    player_number: "3",
    position: "DF",
    country: "South Africa",
    player_name: "Khulumani Ndamane",
    is_captain: "No",
    dob_age: "February 5, 2004 (aged 22)",
    caps: "5",
    goals: "0",
    club: "Mamelodi Sundowns",
    club_location: "South Africa"
  },
  {
    player_number: "4",
    position: "MF",
    country: "South Africa",
    player_name: "Teboho Mokoena",
    is_captain: "No",
    dob_age: "January 24, 1997 (aged 29)",
    caps: "51",
    goals: "9",
    club: "Mamelodi Sundowns",
    club_location: "South Africa"
  },
  {
    player_number: "5",
    position: "MF",
    country: "South Africa",
    player_name: "Thalente Mbatha",
    is_captain: "No",
    dob_age: "March 6, 2000 (aged 26)",
    caps: "15",
    goals: "3",
    club: "Orlando Pirates",
    club_location: "South Africa"
  },
  {
    player_number: "6",
   position: "DF",
   country: "South Africa",
    player_name: "Aubrey Modiba",
    is_captain: "No",
    dob_age: "July 22, 1995 (aged 30)",
    caps: "44",
    goals: "3",
    club: "Mamelodi Sundowns",
    club_location: "South Africa"
  },
  {
    player_number: "7",
   position: "FW",
   country: "South Africa",
    player_name: "Oswin Appollis",
    is_captain: "No",
    dob_age: "August 25, 2001 (aged 24)",
    caps: "26",
    goals: "8",
    club: "Orlando Pirates",
    club_location: "South Africa"
  },
  {
    player_number: "8",
   position: "FW",
   country: "South Africa",
    player_name: "Tshepang Moremi",
    is_captain: "No",
    dob_age: "October 2, 2000 (aged 25)",
    caps: "10",
    goals: "1",
    club: "Orlando Pirates",
    club_location: "South Africa"
  },
  {
    player_number: "9",
   position: "FW",
   country: "South Africa",
    player_name: "Lyle Foster",
    is_captain: "No",
    dob_age: "September 3, 2000 (aged 25)",
    caps: "27",
    goals: "10",
    club: "Burnley",
    club_location: "England"
  },
  {
    player_number: "10",
   position: "FW",
   country: "South Africa",
    player_name: "Relebohile Mofokeng",
    is_captain: "No",
    dob_age: "October 23, 2004 (aged 21)",
    caps: "13",
    goals: "0",
    club: "Orlando Pirates",
    club_location: "South Africa"
  },
  {
    player_number: "11",
   position: "MF",
   country: "South Africa",
    player_name: "Themba Zwane",
    is_captain: "No",
    dob_age: "August 3, 1989 (aged 36)",
    caps: "54",
    goals: "12",
    club: "Mamelodi Sundowns",
    club_location: "South Africa"
  },
  {
    player_number: "12",
   position: "FW",
   country: "South Africa",
    player_name: "Thapelo Maseko",
    is_captain: "No",
    dob_age: "November 11, 2003 (aged 22)",
    caps: "10",
    goals: "1",
    club: "AEL Limassol",
    club_location: "Cyprus"
  },
  {
    player_number: "13",
   position: "MF",
   country: "South Africa",
    player_name: "Sphephelo Sithole",
    is_captain: "No",
    dob_age: "March 3, 1999 (aged 27)",
    caps: "28",
    goals: "1",
    club: "Tondela",
    club_location: "Portugal"
  },
  {
    player_number: "14",
   position: "DF",
   country: "South Africa",
    player_name: "Mbekezeli Mbokazi",
    is_captain: "No",
    dob_age: "September 19, 2005 (aged 20)",
    caps: "10",
    goals: "1",
    club: "Chicago Fire FC",
    club_location: "United States"
  },
  {
    player_number: "15",
   position: "FW",
    player_name: "Iqraam Rayners",
    is_captain: "No",
    dob_age: "December 19, 1995 (aged 30)",
    caps: "14",
    goals: "4",
    club: "Mamelodi Sundowns",
    club_location: "South Africa"
  },
  {
    player_number: "16",
   position: "GK",
   country: "South Africa",
    player_name: "Sipho Chaine",
    is_captain: "No",
    dob_age: "December 14, 1996 (aged 29)",
    caps: "4",
    goals: "0",
    club: "Orlando Pirates",
    club_location: "South Africa"
  },
  {
    player_number: "17",
   position: "FW",
   country: "South Africa",
    player_name: "Evidence Makgopa",
    is_captain: "No",
    dob_age: "June 5, 2000 (aged 26)",
    caps: "26",
    goals: "6",
    club: "Orlando Pirates",
    club_location: "South Africa"
  },
  {
    player_number: "18",
   position: "DF",
   country: "South Africa",
    player_name: "Samukele Kabini",
    is_captain: "No",
    dob_age: "March 15, 2004 (aged 22)",
    caps: "6",
    goals: "0",
    club: "Molde",
    club_location: "Norway"
  },
  {
    player_number: "19",
   position: "DF",
   country: "South Africa",
    player_name: "Nkosinathi Sibisi",
    is_captain: "No",
    dob_age: "September 22, 1995 (aged 30)",
    caps: "20",
    goals: "0",
    club: "Orlando Pirates",
    club_location: "South Africa"
  },
  {
    player_number: "20",
   position: "DF",
   country: "South Africa",
    player_name: "Khuliso Mudau",
    is_captain: "No",
    dob_age: "April 26, 1995 (aged 31)",
    caps: "32",
    goals: "1",
    club: "Mamelodi Sundowns",
    club_location: "South Africa"
  },
  {
    player_number: "21",
   position: "DF",
   country: "South Africa",
    player_name: "Ime Okon",
    is_captain: "No",
    dob_age: "February 20, 2004 (aged 22)",
    caps: "8",
    goals: "1",
    club: "Hannover 96",
    club_location: "Germany"
  },
  {
    player_number: "22",
   position: "GK",
   country: "South Africa",
    player_name: "Ricardo Goss",
    is_captain: "No",
    dob_age: "April 2, 1994 (aged 32)",
    caps: "5",
    goals: "0",
    club: "Siwelele",
    club_location: "South Africa"
  },
  {
    player_number: "23",
   position: "MF",
   country: "South Africa",
    player_name: "Jayden Adams",
    is_captain: "No",
    dob_age: "May 5, 2001 (aged 25)",
    caps: "5",
    goals: "0",
    club: "Mamelodi Sundowns",
    club_location: "South Africa"
  },
  {
    player_number: "24",
   position: "DF",
   country: "South Africa",
    player_name: "Olwethu Makhanya",
    is_captain: "No",
    dob_age: "April 30, 2004 (aged 22)",
    caps: "1",
    goals: "0",
    club: "Philadelphia Union",
    club_location: "United States"
  },
  {
    player_number: "25",
   position: "FW",
   country: "South Africa",
    player_name: "Kamogelo Sebelebele",
    is_captain: "No",
    dob_age: "July 21, 2002 (aged 23)",
    caps: "3",
    goals: "0",
    club: "Orlando Pirates",
    club_location: "South Africa"
  },
  {
    player_number: "26",
    position: "DF",
    country: "South Africa",
    player_name: "Bradley Cross",
    is_captain: "No",
    dob_age: "January 30, 2001 (aged 25)",
    caps: "1",
    goals: "0",
    club: "Kaizer Chiefs",
    club_location: "South Africa"
  }
]