const stadiumData = [
	{
		id: 1,
		name: "BC Place", // Name used in tournament (due to FIFA sponsorship policies)
		alternative_name: "BC Place Vancouver", // Normally used name
		image_url: "https://assets.goal.com/images/v3/getty-2203463797/crop/MM5DIMJZGI5DEMZVHA5G433XMU5DQORWHE======/GettyImages-2203463797.jpg?auto=webp&format=pjpg&width=3840&quality=60",
		image_source: "Goal.com",
		country: "Canada",
		flag_icon: "fi fi-ca",
		city: "Vancouver",
		capacity: 45000,
		latitude: 49.276516,
		longitude: -123.111779
	},
	{
		id: 2,
		name: "Toronto Stadium",
		alternative_name: "BMO Field",
		image_url: "https://gazettengr.com/wp-content/uploads/Untitled-1-2403.png",
		image_source: "Peoples Gazette Nigeria",
		country: "Canada",
		flag_icon: "fi fi-ca",
		city: "Toronto",
		capacity: 54000,
		latitude: 43.633357,
		longitude: -79.418267
	},
	{
		id: 3,
		name: "Dallas Stadium",
		alternative_name: "AT&T Stadium",
		image_url: "https://www.hksinc.com/wp-content/uploads/2009/10/ATT_economic-1.jpg",
		image_source: "HKS Architects",
		country: "United States",
		flag_icon: "fi fi-us",
		city: "Dallas",
		accurate_location: "Arlington, Texas", // The more accurate venue as some are not actually in the cities listed but the cities are more recognizable
		capacity: 94000,
		latitude: 32.747995,
		longitude: -97.093869
	},
	{
		id: 4,
		name: "New York/New Jersey Stadium",
		alternative_name: "MetLife Stadium",
		image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Metlife_stadium_%28Aerial_view%29.jpg/1280px-Metlife_stadium_%28Aerial_view%29.jpg",
		image_source: "Wikipedia",
		country: "United States",
		flag_icon: "fi fi-us",
		city: "New York/New Jersey",
		accurate_location: "East Rutherford, New Jersey",
		capacity: 82500,
		latitude: 40.813976,
		longitude: -74.075811
	},
	{
		id: 5,
		name: "Atlanta Stadium",
		alternative_name: "Mercedes-Benz Stadium",
		image_url: "https://media.architecturaldigest.com/photos/55f9e1d99bff6eeb3a241a7b/master/pass/dam-images-daily-2015-08-atlanta-falcons-stadium-atlanta-falcons-mercedes-benz-stadium-01.jpg",
		image_source: "Architectural Digest",
		country: "United States",
		flag_icon: "fi fi-us",
		city: "Atlanta",
		capacity: 75000,
		latitude: 33.755909,
		longitude: -84.401752
	},
	{
		id: 6,
		name: "Kansas City Stadium",
		alternative_name: "Arrowhead Stadium",
		image_url: "https://www.archpaper.com/wp-content/uploads/2024/02/caojicquyzq9uf8auwgs.jpeg",
		image_source: "The Architect's Newspaper",
		country: "United States",
		flag_icon: "fi fi-us",
		city: "Kansas City",
		capacity: 73000,
		latitude: 39.048990,
		longitude: -94.484573
	},
	{
		id: 7,
		name: "Houston Stadium",
		alternative_name: "NRG Stadium",
		image_url: "https://static.wikia.nocookie.net/collegefootballmania/images/6/6a/Reliantstadium.jpg/revision/latest?cb=20140509110355",
		image_source: "Fandom - American Football Wiki",
		country: "United States",
		flag_icon: "fi fi-us",
		city: "Houston",
		capacity: 72000,
		latitude: 29.684968,
		longitude: -95.410831
	},
	{
		id: 8,
		name: "San Francisco Bay Area Stadium",
		alternative_name: "Levi's Stadium",
		image_url: "https://www.hntb.com/wp-content/uploads/2026/02/01_Levis_Hero-scaled.jpg",
		image_source: "Schindler Group",
		country: "United States",
		flag_icon: "fi fi-us",
		city: "San Francisco Bay Area",
		accurate_location: "Santa Clara, California",
		capacity: 71000,
		latitude: 37.403710,
		longitude: -121.970247
	},
	{
		id: 9,
		name: "Los Angeles Stadium",
		alternative_name: "SoFi Stadium",
		image_url: "https://www.hksinc.com/wp-content/uploads/2022/01/SoFi_Factsbody2.jpg",
		image_source: "HKS Architects",
		country: "United States",
		flag_icon: "fi fi-us",
		city: "Los Angeles",
		accurate_location: "Inglewood, California",
		capacity: 70000,
		latitude: 33.953461,
		longitude: -118.339008
	},
	{
		id: 10,
		name: "Philadelphia Stadium",
		alternative_name: "Lincoln Financial Field",
		image_url: "https://images.axios.com/KlVopXS5588NXOoghh8D23XhbKI=/0x0:0x0/1366x768/2024/10/15/1729018276300.jpg",
		image_source: "Axios",
		country: "United States",
		flag_icon: "fi fi-us",
		city: "Philadelphia",
		capacity: 69000,
		latitude: 39.900811,
		longitude: -75.167427
	},
	{
		id: 11,
		name: "Seattle Stadium",
		alternative_name: "Lumen Field",
		image_url: "https://images.trvl-media.com/place/502713/41a0deed-5513-4c1c-af1e-2ea7ce48f3d7.jpg",
		image_source: "Expedia",
		country: "United States",
		flag_icon: "fi fi-us",
		city: "Seattle",
		capacity: 69000,
		latitude: 47.595543,
		longitude: -122.331583
	},
	{
		id: 12,
		name: "Boston Stadium",
		alternative_name: "Gillette Stadium",
		image_url: "https://populous.com/uploads/2018/01/Gillette_Stadium_Populous.jpg",
		image_source: "Populous",
		country: "United States",
		flag_icon: "fi fi-us",
		city: "Boston",
		accurate_location: "Foxborough, Massachusetts",
		capacity: 65000,
		latitude: 42.090928,
		longitude: -71.264158
	},
	{
		id: 13,
		name: "Miami Stadium",
		alternative_name: "Hard Rock Stadium",
		image_url: "https://icxgroup.com/wp-content/uploads/hard-rock-stadium-hero.jpg",
		image_source: "ICX Group",
		country: "United States",
		flag_icon: "fi fi-us",
		city: "Miami",
		accurate_location: "Miami Gardens, Florida",
		capacity: 65000,
		latitude: 25.957905,
		longitude: -80.238889
	},
	{
		id: 14,
		name: "Estadio Monterrey",
		alternative_name: "Estadio BBVA",
		image_url: "https://populous.com/uploads/2018/01/MNTRYMXSOC_0363_JorgeToboada.jpg",
		image_source: "Populous",
		country: "Mexico",
		flag_icon: "fi fi-mx",
		city: "Monterrey",
		accurate_location: "Guadalupe",
		capacity: 53500,
		latitude: 25.669181,
		longitude: -100.244429
	},
	{
		id: 15,
		name: "Estadio Guadalajara",
		alternative_name: "Estadio Akron",
		image_url: "https://assets.goal.com/images/v3/getty-2225674157/crop/MM5DINJUGQ5DENJVGY5G433XMU5DCNZUHIYTCNI=/GettyImages-2225674157.jpg?auto=webp&format=pjpg&width=3840&quality=60",
		image_source: "Goal.com",
		country: "Mexico",
		flag_icon: "fi fi-mx",
		city: "Guadalajara",
		accurate_location: "Zapopan",
		capacity: 48000,
		latitude: 20.681915,
		longitude: -103.462656
	},
	{
		id: 16,
		name: "Estadio Azteca",
		alternative_name: "Estadio Banorte",
		image_url: "https://statics-maker.llt-services.com/ban/images/2026/05/13/original/f55c0af7-7d27-429b-9d80-a9f288ab6e81-234.jpg",
		image_source: "Estadio Banorte",
		country: "Mexico",
		flag_icon: "fi fi-mx",
		city: "Mexico City",
		capacity: 83000,
		latitude: 19.303058,
		longitude:  -99.150447
	}
]