const teamData = [
	{
		id: 1,
		name: "Mexico",
		group: "A",
		flag_icon: "fi fi-mx",
		coach: "Javier Aguirre",
		coach_nationality: "fi fi-mx",
		fifa_code: "MEX",
		are_hosts: "Yes",
		confederation: "CONCACAF",
		fifa_ranking: 15,
		nicknames: ["El Tri", "El Tricolor"],
		association: "Federación Mexicana de Fútbol (FMF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/Mexico_national_football_team_crest.svg/330px-Mexico_national_football_team_crest.svg.png",
		no_wc_past_appearances: 17,
		debut: "",
		wc_best_result: "Quarter-finals (1970, 1986)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Group Stage" //Perfomance in Qatar 2022 
	},
	{
		id: 2,
		name: "Czechia",
		group: "A",
		flag_icon: "fi fi-cz",
		coach: "Miroslav Koubek",
		coach_nationality: "fi fi-cz",
		fifa_code: "CZE",
		are_hosts: "No",
		confederation: "UEFA",
		fifa_ranking: 41,
		nicknames: ["Narod'ak (The National Team)", "Repre (The Representatives)"],
		association: "Football Association of the Czech Republic (FAČR)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/7/76/Czech_Republic_national_football_team_logo.svg/500px-Czech_Republic_national_football_team_logo.svg.png",
		no_wc_past_appearances: 1,
		wc_best_result: "Group stage (2006)",
		played_in_last_wc: "No",
		last_wc_app: "Germany 2006", // For teams who didn't qualify for Qatar
		previous_wc_perf: "Group stage" //Performance in previous World Cup appearance if they didn't play in Qatar
	},
	{
		id: 3,
		name: "South Africa",
		group: "A",
		flag_icon: "fi fi-za",
		coach: "Hugo Broos",
		coach_nationality: "fi fi-be",
		fifa_code: "RSA",
		are_hosts: "No",
		confederation: "CAF",
		fifa_ranking: 60,
		nicknames: "Bafana Bafana",
		association: "South African Football Association (SAFA)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e7/South_Africa_national_soccer_team_logo.svg/500px-South_Africa_national_soccer_team_logo.svg.png",
		no_wc_past_appearances: 3,
		debut: "France 1998",
		wc_best_result: "Group stage (1998, 2002, 2010)",
		played_in_last_wc: "No",
		last_wc_app: "South Africa 2010",
		previous_wc_perf: "Group stage"
	},
	{
		id: 4,
		name: "South Korea",
		group: "A",
		flag_icon: "fi fi-kr",
		coach: "Hong Myung-bo",
		flag_icon: "fi fi-kr",
		fifa_code: "KOR",
		are_hosts: "No",
		confederation: "AFC",
		fifa_ranking: 25,
		nicknames: ["Taegeuk Warriors", "Tigers of Asia"],
		association: "Korea Football Association (KFA)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5e/Korea_Football_Association_logo.svg/330px-Korea_Football_Association_logo.svg.png",
		no_wc_past_appearances: 10,
		wc_best_result: "Fourth place (2002)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Round of 16"
	},
	{
		id: 5,
		name: "Canada",
		group: "B",
		flag_icon: "fi fi-ca",
		coach: "Jesse Marsch",
		coach_nationality: "fi fi-us",
		fifa_code: "CAN",
		are_hosts: "Yes",
		confederation: "CONCACAF",
		fifa_ranking: 30,
		nicknames: ["Les Rouges (The Reds)", "The Canucks", "The Maple Leaf Team"],
		association: "Canadian Soccer Association (CSA)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Canadian_Soccer_Association_logo.svg/500px-Canadian_Soccer_Association_logo.svg.png",
		no_wc_past_appearances: 2,
		wc_best_result: "Group stage (1986, 2022)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Group stage"
	},
	{
		id: 6,
		name: "Bosnia & Herzegovina",
		group: "B",
		flag_icon: "fi fi-ba",
		coach: "Sergej Barbarez",
		coach_nationality: "fi fi-ba",
		fifa_code: "BIH",
		are_hosts: "No",
		confederation: "UEFA",
		fifa_ranking: 65,
		nicknames: ["Zmajevi (The Dragons)", "Zlatni Ljiljani (Golden Lilies)"],
		association: "Nogometni/Fudbalski Savez Bosne i Hercegovine (N/FSBiH)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/d/da/Football_Association_of_Bosnia_and_Herzegovina_logo.svg/500px-Football_Association_of_Bosnia_and_Herzegovina_logo.svg.png",
		no_wc_past_appearances: 1,
		wc_best_result: "Group stage (2014)",
		played_in_last_wc: "No",
		last_wc_app: "Brazil 2014",
		previous_wc_perf: "Group stage"
	},
	{
		id: 7,
		name: "Qatar",
		group: "B",
		flag_icon: "fi fi-qa",
		coach: "Julen Lopetegui",
		coach_nationality: "fi fi-es",
		fifa_code: "QAT",
		are_hosts: "No",
		confederation: "AFC",
		fifa_ranking: 55,
		nicknames: "العنابي (The Maroon One)",
		association: "Qatar Football Association (QFA)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/Qatar_Football_Association_logo.svg/500px-Qatar_Football_Association_logo.svg.png",
		no_wc_past_appearances: 1,
		wc_best_result: "Group stage (2022)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Group stage"
	},
	{
		id: 8,
		name: "Switzerland",
		group: "B",
		flag_icon: "fi fi-ch",
		coach: "Murat Yakin",
		coach_nationality: "fi fi-ch",
		fifa_code: "SUI",
		are_hosts: "No",
		confederation: "UEFA",
		fifa_ranking: 19,
		nicknames: ["A-Team Nati (National Team)", "Rossocrociati (Red Crosses)", "Devil Rouges (Red Devils)"],
		association: "Association Suisse de Football, Associazione Svizzera di Football, Shweizerischer Fussballverband (ASF-SFV)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a0/Swiss_Football_Association_logo.svg/500px-Swiss_Football_Association_logo.svg.png",
		no_wc_past_appearances: 12,
		wc_best_result: "Quarter-finals (1934, 1938, 1954)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Round of 16"
	},
	{
		id: 9,
		name: "Brazil",
		group: "C",
		flag_icon: "fi fi-br",
		coach: "Carlo Ancelotti",
		coach_nationality: "fi fi-it",
		fifa_code: "BRA",
		are_hosts: "No",
		confederation: "CONMEBOL",
		fifa_ranking: 6,
		nicknames: "Selecao (The Selection), Canarinho (Little Canary), Verde-Amarela (Green-Yellow), A Maior do Mundo (Best in the World)",
		association: "Confederação Brasileira de Futebol (CBF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Confedera%C3%A7%C3%A3o_Brasileira_de_Futebol_logo_%282020%29.svg/500px-Confedera%C3%A7%C3%A3o_Brasileira_de_Futebol_logo_%282020%29.svg.png",
		no_wc_past_appearances: 22,
		wc_best_result: "Champions (1958, 1962, 1970, 1994, 2002)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Quarter-finals"
	},
	{
		id: 10,
		name: "Haiti",
		group: "C",
		flag_icon: "fi fi-ht",
		coach: "Sebastien Migne",
		coach_nationality: "fi fi-fr",
		fifa_code: "HAI",
		are_hosts: "No",
		confederation: "CONCACAF",
		fifa_ranking: 83,
		nicknames: "Les Grenadiers (The Grenadiers), Le Rouge et Bieu (The Red and Blue), Les Bicolores (The Bicolor), La Selection Nationale (The National Selection)",
		association: "Fédération Haïtienne de Football (FHF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/e/e7/Federation_Haitienne_de_Football.png",
		no_wc_past_appearances: 1,
		wc_best_result: "Group stage (1974)",
		played_in_last_wc: "No",
		last_wc_app: "West Germany 1974",
		previous_wc_perf: "Group stage"
	},
	{
		id: 11,
		name: "Morocco",
		group: "C",
		flag_icon: "fi fi-ma",
		coach: "Mohamed Ouahbi",
		coach_nationality: "fi fi-ma",
		fifa_code: "MAR",
		are_hosts: "No",
		confederation: "CAF",
		fifa_ranking: 8,
		nicknames: "أُسُودُ الأَطلَس (The Atlas Lions)",
		association: "Royal Morrocan Football Federation (RMFF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/Royal_Moroccan_Football_Federation_logo.svg/500px-Royal_Moroccan_Football_Federation_logo.svg.png",
		no_wc_past_appearances: 5,
		wc_best_result: "Fourth place (2022)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Fourth place"
	},
	{
		id: 12,
		name: "Scotland",
		group: "C",
		flag_icon: "fi fi-gb-sct",
		coach: "Steve Clarke",
		coach_nationality: "fi fi-gb-sct",
		fifa_code: "SCO",
		are_hosts: "No",
		confederation: "UEFA",
		fifa_ranking: 43,
		nicknames: "The Tartan Army (supporters)",
		association: "Scottish Football Association (SFA)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Scotland_national_football_team_logo_2014.svg/500px-Scotland_national_football_team_logo_2014.svg.png",
		no_wc_past_appearances: 8,
		wc_best_result: "Group stage (1954, 1958, 1974, 1978, 1982, 1986, 1990, 1998)",
		played_in_last_wc: "No",
		last_wc_app: "France 1998",
		previous_wc_perf: "Group stage"
	},
	{
		id: 13,
		name: "United States",
		group: "D",
		flag_icon: "fi fi-us",
		coach: "Mauricio Pochettino",
		coach_nationality: "fi fi-ar",
		fifa_code: "USA",
		are_hosts: "Yes",
		confederation: "CONCACAF",
		fifa_ranking: 16,
		nicknames: ["The USMNT", "The Stars and Stripes"],
		association: "United States Soccer Federation (USSF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/United_States_Soccer_Federation_logo.svg/330px-United_States_Soccer_Federation_logo.svg.png",
		no_wc_past_appearances: 11,
		wc_best_result: "Third place (1930)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Round of 16"
		
	},
	{
		id: 14,
		name: "Australia",
		group: "D",
		flag_icon: "fi fi-au",
		coach: "Tony Popovic",
		coach_nationality: "fi fi-au",
		fifa_code: "AUS",
		are_hosts: "No",
		confederation: "AFC",
		fifa_ranking: 27,
		nicknames: "The Socceroos",
		association: "Football Australia",
		assc_crest: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Australia_national_football_team_badge.svg/500px-Australia_national_football_team_badge.svg.png",
		no_wc_past_appearances: 6,
		wc_best_result: "Round of 16 (2006, 2022)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Round of 16"
	},
	{
		id: 15,
		name: "Paraguay",
		group: "D",
		flag_icon: "fi fi-py",
		coach: "Gustavo Alfaro",
		coach_nationality: "fi fi-ar",
		fifa_code: "PAR",
		are_hosts: "No",
		confederation: "CONMEBOL",
		fifa_ranking: 40,
		nicknames: "Los Guaranies (The Guaranies), La Albirroja (The White and Red)",
		association: "Asociación Paraguaya de Fútbol (APF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Asociaci%C3%B3n_Paraguaya_de_F%C3%BAtbol_logo.svg/500px-Asociaci%C3%B3n_Paraguaya_de_F%C3%BAtbol_logo.svg.png",
		no_wc_past_appearances: 8,
		wc_best_result: "Quarter-finals (2010)",
		played_in_last_wc: "No",
		last_wc_app: "South Africa 2010",
		previous_wc_perf: "Quarter-finals"
	},
	{
		id: 16,
		name: "Türkiye",
		group: "D",
		flag_icon: "fi fi-tr",
		coach: "Vincenzo Montella",
		coach_nationality: "fi fi-it",
		fifa_code: "TUR",
		are_hosts: "No",
		confederation: "UEFA",
		fifa_ranking: 22,
		nicknames: ["Ay-Yildizlilar (The Crescent Stars)", "Bizim Cocuklar (Our Boys)"],
		association: "Türkiye Futbol Federasyonu (TFF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/7/70/Turkish_Football_Federation_crest.svg/500px-Turkish_Football_Federation_crest.svg.png",
		no_wc_past_appearances: 2,
		wc_best_result: "Third place (2002)",
		played_in_last_wc: "No",
		last_wc_app: "South Korea/Japan 2002",
		previous_wc_perf: "Third place"
		
	},
	{
		id: 17,
		name: "Côte d'Ivoire",
		group: "E",
		flag_icon: "fi fi-ci",
		coach: "Emerse Faé",
		coach_nationality: "fi fi-ci",
		fifa_code: "CIV",
		are_hosts: "No",
		confederation: "CAF",
		fifa_ranking: 34,
		nicknames: "Les Éléphants (The Elephants)",
		association: "Fédération Ivorienne de Football (FIF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Cote_Divoire_Enblem.png/330px-Cote_Divoire_Enblem.png",
		no_wc_past_appearances: 3,
		wc_best_result: "Group stage (2006, 2010, 2014)",
		played_in_last_wc: "No",
		last_wc_app: "Brazil 2014",
		previous_wc_perf: "Group stage"
		
	},
	{
		id: 18,
		name: "Curaçao",
		group: "E",
		flag_icon: "fi fi-cw",
		coach: "Dick Advocaat",
		coach_nationality: "fi fi-nl",
		fifa_code: "CUW",
		are_hosts: "No",
		confederation: "CONCACAF",
		fifa_ranking: 82,
		nicknames: "The Blue Wave",
		association: "Federashon Futbòl Kòrsou (FFK)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1c/Curacao_Football_Federation.svg/500px-Curacao_Football_Federation.svg.png",
		no_wc_past_appearances: 0,
	},
	{
		id: 19,
		name: "Ecuador",
		group: "E",
		flag_icon: "fi fi-ec",
		coach: "Sebastián Beccacece",
		coach_nationality: "fi fi-ar",
		fifa_code: "ECU",
		are_hosts: "No",
		confederation: "CONMEBOL",
		fifa_ranking: 23,
		nicknames: ["La Tri (The Tri)", "La Tricolor (The Tricolours)", "La Selección (The Selection)"],
		association: "Federación Ecuatoriana de Fútbol (FEF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/b/ba/Ecuador_national_football_team.png",
		no_wc_past_appearances: 4,
		wc_best_result: "Round of 16 (2006)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Group stage"
	},
	{
		id: 20,
		name: "Germany",
		group: "E",
		flag_icon: "fi fi-de",
		coach: "Julian Nagelsmann",
		coach_nationality: "fi fi-de",
		fifa_code: "GER",
		are_hosts: "No",
		confederation: "UEFA",
		fifa_ranking: 10,
		nicknames: "Die Mannschaft (The Team)",
		association: "Deutscher Fußball-Bund (DFB)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e3/DFBEagle.svg/250px-DFBEagle.svg.png",
		no_wc_past_appearances: 20,
		wc_best_result: "Champions (1954, 1974, 1990, 2014)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Group stage"
	},
	{
		id: 21,
		name: "Japan",
		group: "F",
		flag_icon: "fi fi-jp",
		coach: "Hajime Moriyasu",
		coach_nationality: "fi fi-jp",
		fifa_code: "JPN",
		are_hosts: "No",
		confederation: "AFC",
		fifa_ranking: 18,
		nicknames: "サムライ・ブルー (Samurai Blue)",
		association: "Japan Football Association",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/8/84/Japan_national_football_team_crest.svg/250px-Japan_national_football_team_crest.svg.png",
		no_wc_past_appearances: 7,
		wc_best_result: "Round of 16 (2002, 2010, 2018, 2022)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Round of 16"
		
	},
	{
		id: 22,
		name: "Netherlands",
		group: "F",
		flag_icon: "fi fi-nl",
		coach: "Ronald Koeman",
		coach_nationality: "fi fi-nl",
		fifa_code: "NED",
		are_hosts: "No",
		confederation: "UEFA",
		fifa_ranking: 7,
		nicknames: "Oranje",
		association: "Koninklijke Nederlandse Voetbalbond (KNVB)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/7/78/Netherlands_national_football_team_logo.svg/500px-Netherlands_national_football_team_logo.svg.png",
		no_wc_past_appearances: 11,
		wc_best_result: "Runners-up (1974, 1978, 2010)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Quarter-finals"
	},
	{
		id: 23,
		name: "Sweden",
		group: "F",
		flag_icon: "fi fi-se",
		coach: "Graham Potter",
		coach_nationality: "fi fi-gb-eng",
		fifa_code: "SWE",
		are_hosts: "No",
		confederation: "UEFA",
		fifa_ranking: 38,
		nicknames: "Blågult (The Blue and Yellow)",
		association: "Svenska Fotbollförbundet (SvFF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/Sweden_national_football_team_badge.svg/250px-Sweden_national_football_team_badge.svg.png",
		no_wc_past_appearances: 12,
		wc_best_result: "Runners-up (1958)",
		played_in_last_wc: "No",
		last_wc_app: "Russia 2018",
		previous_wc_perf: "Quarter-finals"
	},
	{
		id: 24,
		name: "Tunisia",
		group: "F",
		flag_icon: "fi fi-tn",
		coach: "Sabri Lamouchi",
		coach_nationality: "fi fi-fr",
		fifa_code: "TUN",
		are_hosts: "No",
		confederation: "CAF",
		fifa_ranking: 44,
		nicknames: "نسور قرطاج (Eagles of Carthage)",
		association: "Tunisian Football Federation (TFF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c4/Tunisia_national_football_team_logo.png/250px-Tunisia_national_football_team_logo.png",
		no_wc_past_appearances: 6,
		wc_best_result: "Group stage (1978, 1998, 2002, 2006, 2018, 2022)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Group stage"
	},
	{
		id: 25,
		name: "Belgium",
		group: "G",
		flag_icon: "fi fi-be",
		coach: "Rudi Garcia",
		coach_nationality: "fi fi-es",
		fifa_code: "BEL",
		are_hosts: "No",
		confederation: "UEFA",
		fifa_ranking: 9,
		nicknames: "De Rode Duivels, Les Diables Rouges, Die Roten Teufel (The Red Devils)",
		association: "Royal Belgian Football Association (RBFA)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Royal_Belgian_FA_logo_2019.svg/330px-Royal_Belgian_FA_logo_2019.svg.png",
		no_wc_past_appearances: 14,
		wc_best_result: "Third place (2018)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Group stage"
	},
	{
		id: 26,
		name: "Egypt",
		group: "G",
		flag_icon: "fi fi-eg",
		coach: "Hossam Hassan",
		coach_nationality: "fi fi-eg",
		fifa_code: "EGY",
		are_hosts: "No",
		confederation: "CAF",
		fifa_ranking: 29,
		nicknames: "The Pharoahs",
		association: "Egyptian Football Association (EFA)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f8/Egyptian_Football_Association_logo.svg/500px-Egyptian_Football_Association_logo.svg.png",
		no_wc_past_appearances: 3,
		wc_best_result: "Round of 16 (1934)",
		played_in_last_wc: "No",
		last_wc_app: "Russia 2018",
		previous_wc_perf: "Group Stage"
	},
	{
		id: 27,
		name: "Iran",
		group: "G",
		flag_icon: "fi fi-ir",
		coach: "Amir Ghalenoei",
		coach_nationality: "fi fi-ir",
		fifa_code: "IRN",
		are_hosts: "No",
		confederation: "AFC",
		fifa_ranking: 21,
		nicknames: "Team Melli (National Team)",
		association: "Football Federation Islamic Republic of Iran (FFIRI)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d6/Football_Federation_Islamic_Republic_of_Iran_logo.svg/330px-Football_Federation_Islamic_Republic_of_Iran_logo.svg.png",
		no_wc_past_appearances: 6,
		wc_best_result: "",
		played_in_last_wc: "Yes",
		last_wc_perf: "Group stage"
	},
	{
		id: 28,
		name: "New Zealand",
		group: "G",
		flag_icon: "fi fi-nz",
		coach: "Darren Bazeley",
		coach_nationality: "fi fi-gb-eng",
		fifa_code: "NZL",
		are_hosts: "No",
		confederation: "OFC",
		fifa_ranking: 85,
		nicknames: "All Whites",
		association: "New Zealand Football (NZF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/New_Zealand_Football_Crest_2022.svg/500px-New_Zealand_Football_Crest_2022.svg.png",
		no_wc_past_appearances: 2,
		wc_best_result: "Group stage (1982, 2010)",
		played_in_last_wc: "No",
		last_wc_app: "South Africa 2010",
		previous_wc_perf: "Group stage"
	},
	{
		id: 29,
		name: "Cape Verde",
		group: "H",
		flag_icon: "fi fi-cv",
		coach: "Bubista",
		coach_nationality: "fi fi-cv",
		fifa_code: "CPV",
		are_hosts: "No",
		confederation: "CAF",
		fifa_ranking: 69,
		nicknames: ["Tubarões Azuis (Blue Sharks)", "Crioulos (Creoles)"],
		association: "Federação Caboverdiana de Futebol (FCF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/5/57/Cape_Verde_national_football_team.svg/250px-Cape_Verde_national_football_team.svg.png",
		no_wc_past_appearances: 0,
	},
	{
		id: 30,
		name: "Saudi Arabia",
		group: "H",
		flag_icon: "fi fi-sa",
		coach: "Georgios Donis",
		coach_nationality: "fi fi-gr",
		fifa_code: "KSA",
		are_hosts: "No",
		confederation: "AFC",
		association: "Saudi Arabian Football Federation (SAFF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/e/ee/Saudi_Arabia_national_football_team_logo.svg/500px-Saudi_Arabia_national_football_team_logo.svg.png",
		fifa_ranking: 61,
		nicknames: ["الأخضر (al-'Akhḍar, 'The Green One')","الصقور العربية (as-Suqūr Al-‘Arabiyyah, 'Arabian Falcons')","الصقور الخضر (as-Suqūr al-Khoḍur, 'The Green Falcons')"],
		no_wc_past_appearances: 6,
		debut: "",
		wc_best_result: "Round of 16 (1994)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Group stage"
	},
	{
		id: 31,
		name: "Spain",
		group: "H",
		flag_icon: "fi fi-es",
		coach: "Luis de la Fuente",
		coach_nationality: "fi fi-es",
		fifa_code: "ESP",
		are_hosts: "No",
		confederation: "UEFA",
		fifa_ranking: 2,
		nicknames: "La Roja (The Red One)",
		association: "Real Federación Española de Fútbol (RFEF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/3/39/Spain_national_football_team_crest.svg/330px-Spain_national_football_team_crest.svg.png",
		no_wc_past_appearances: 16,
		wc_best_result: "Champions (2010)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Round of 16"
	},
	{
		id: 32,
		name: "Uruguay",
		group: "H",
		flag_icon: "fi fi-uy",
		coach: "Marcelo Bielsa",
		coach_nationality: "fi fi-ar",
		fifa_code: "URU",
		are_hosts: "No",
		confederation: "CONMEBOL",
		fifa_ranking: 17,
		nicknames: ["La Celeste (The Sky Blues)", "Los Charrúas (The Charrúas)"],
		association: "Asociación Uruguaya de Fútbol (AUF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/4/43/Uruguay_national_football_team_seal.svg/250px-Uruguay_national_football_team_seal.svg.png",
		no_wc_past_appearances: 14,
		wc_best_result: "Champions (1930, 1950)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Group stage"
	},
	{
		id: 33,
		name: "France",
		group: "I",
		flag_icon: "fi fi-fr",
		coach: "Didier Deschamps",
		coach_nationality: "fi fi-fr",
		fifa_code: "FRA",
		are_hosts: "No",
		confederation: "UEFA",
		fifa_ranking: 1,
		nicknames: "Les Bleus (The Blues)",
		association: "Fédération Française de Football (FFF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/France_national_football_team_seal.svg/330px-France_national_football_team_seal.svg.png",
		no_wc_past_appearances: 16,
		wc_best_result: "Champions (1998, 2018)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Runners-up"
	},
	{
		id: 34,
		name: "Iraq",
		group: "I",
		flag_icon: "fi fi-iq",
		coach: "Graham Arnold",
		coach_nationality: "fi fi-au",
		fifa_code: "IRQ",
		are_hosts: "No",
		confederation: "AFC",
		fifa_ranking: 57,
		nicknames: "Usood al-Rafidayn (Lions of Mesopotamia)",
		association: "Iraq Football Association (IFA)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Iraq_National_Team_Badge_2021_v1.svg/500px-Iraq_National_Team_Badge_2021_v1.svg.png",
		no_wc_past_appearances: 1,
		wc_best_result: "Group stage (1986)",
		played_in_last_wc: "No",
		last_wc_app: "Mexico 1986",
		previous_wc_perf: "Group stage"
	},
	{
		id: 35,
		name: "Norway",
		group: "I",
		flag_icon: "fi fi-no",
		coach: "Ståle Solbakken",
		fifa_code: "NOR",
		are_hosts: "No",
		confederation: "UEFA",
		fifa_ranking: 31,
		nicknames: ["Røde, Hvite, Blå (Red, White and Blue)","Landslaget Drillos (National Team)"],
		association: "Norges Fotballforbund (NFF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6c/Norway_national_football_team_logo.svg/330px-Norway_national_football_team_logo.svg.png",
		no_wc_past_appearances: 3,
		wc_best_result: "Round of 16 (1938, 1998)",
		played_in_last_wc: "No",
		last_wc_app: "France 1998",
		previous_wc_perf: "Round of 16"
	},
	{
		id: 36,
		name: "Senegal",
		group: "I",
		flag_icon: "fi fi-sn",
		coach: "Pape Thiaw",
		coach_nationality: "fi fi-sn",
		fifa_code: "SEN",
		are_hosts: "No",
		confederation: "CAF",
		fifa_ranking: 14,
		nicknames: "Lions de la Téranga (The Lions of Teranga)",
		association: "Fédération Sénégalaise de Football (FSF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/1/16/Senegalese_Football_Federation_logo.svg/500px-Senegalese_Football_Federation_logo.svg.png",
		no_wc_past_appearances: 3,
		wc_best_result: "Quarter-finals (2002)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Round of 16"
	},
	{
		id: 37,
		name: "Algeria",
		group: "J",
		flag_icon: "fi fi-dz",
		coach: "Vladimir Petković",
		coach_nationality: "fi fi-ba",
		fifa_code: "ALG",
		are_hosts: "No",
		confederation: "CAF",
		fifa_ranking: 28,
		nicknames: ["الخُضر (The Greens)", "الأفناك (The Fennecs)", "مُحَارِبِي الصَّحْرَاء (The Desert Warriors)"],
		association: "Fédération Algérienne de Football (FAF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/2/2d/Algerian_NT_%28logo%29.png",
		no_wc_past_appearances: 4,
		wc_best_result: "Round of 16 (2014)",
		played_in_last_wc: "No",
		last_wc_app: "Brazil 2014",
		previous_wc_perf: "Round of 16"
	},
	{
		id: 38,
		name: "Argentina",
		group: "J",
		flag_icon: "fi fi-ar",
		coach: "Lionel Scaloni",
		coach_nationality: "fi fi-ar",
		fifa_code: "ARG",
		are_hosts: "No",
		are_champions: "Yes",
		confederation: "CONMEBOL",
		fifa_ranking: 3,
		nicknames: ["La Selección (The Selection)", "La Albiceleste (The White and Sky Blue)"],
		association: "Asociación del Fútbol Argentino (AFA)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c1/Argentina_national_football_team_logo.svg/330px-Argentina_national_football_team_logo.svg.png",
		no_wc_past_appearances: 18,
		wc_best_result: "Champions (1978, 1986, 2022)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Champions"

	},
	{
		id: 39,
		name: "Austria",
		group: "J",
		flag_icon: "fi fi-at",
		coach: "Ralf Rangnick",
		coach_nationality: "fi fi-de",
		fifa_code: "AUT",
		are_hosts: "No",
		confederation: "UEFA",
		fifa_ranking: 24,
		nicknames: ["Das Team (The Team)", "Burschen (The Boys)", "Unsere Burschen (Our Boys)"],
		association: "Österreichischer Fußball-Bund (ÖFB)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b7/Austria_national_football_team_crest.svg/330px-Austria_national_football_team_crest.svg.png",
		no_wc_past_appearances: 8,
		wc_best_result: "Third place (1954)",
		played_in_last_wc: "No",
		last_wc_app: "France 1998",
		previous_wc_perf: "Group stage"
	},
	{
		id: 40,
		name: "Jordan",
		group: "J",
		flag_icon: "fi fi-jo",
		coach: "Jamal Sellami",
		coach_nationality: "fi fi-ma",
		second_coach_nationality: "fi fi-jo", // Jamal Sellami was given Jordanian citizenship
		fifa_code: "JOR",
		are_hosts: "No",
		confederation: "AFC",
		fifa_ranking: 63,
		nicknames: "النشامى (The Chivalrous Ones)",
		association: "Jordan Football Association (JFA)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Jordan_national_football_team_logo_2024.svg/500px-Jordan_national_football_team_logo_2024.svg.png",
		no_wc_past_appearances: 0
	},
	{
		id: 41,
		name: "Colombia",
		group: "K",
		flag_icon: "fi fi-co",
		coach: "Néstor Lorenzo",
		coach_nationality: "fi fi-ar",
		fifa_code: "COL",
		are_hosts: "No",
		confederation: "CONMEBOL",
		fifa_ranking: 13,
		nicknames: ["Los Cafeteros (The Coffee Growers)", "La Tricolor (The Tricolour)", "La Sele (The Sele)"],
		association: "Federación Colombiana de Fútbol (FCF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/FCF-Logo-2023.svg/500px-FCF-Logo-2023.svg.png",
		no_wc_past_appearances: 6,
		wc_best_result: "Quarter-finals (2014)",
		played_in_last_wc: "No",
		last_wc_app: "Russia 2018",
		previous_wc_perf: "Round of 16"
	},
	{
		id: 42,
		name: "DR Congo",
		group: "K",
		flag_icon: "fi fi-cd",
		coach: "Sebastien Desabre",
		coach_nationality: "fi fi-fr",
		fifa_code: "COD",
		are_hosts: "No",
		confederation: "CAF",
		fifa_ranking: 46,
		nicknames: ["Léopards (Leopards)", "Guerriers de l'Équateur (Warriors of the Equator)", "La Céleste (The Skyblue)"],
		association: "Fédération Congolaise de Football-Association (FECOFA)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/6/62/Congolese_Association_Football_Federation_logo.png",
		no_wc_past_appearances: 1,
		wc_best_result: "Group stage (1974)",
		played_in_last_wc: "No",
		last_wc_app: "West Germany 1974",
		previous_wc_perf: "Group stage"
	},
	{
		id: 43,
		name: "Portugal",
		group: "K",
		flag_icon: "fi fi-pt",
		coach: "Roberto Martinez",
		coach_nationality: "fi fi-es",
		fifa_code: "POR",
		are_hosts: "No",
		confederation: "UEFA",
		fifa_ranking: 5,
		nicknames: ["Seleção das Quinas (Team of the Quincunxes)","Lusos (Lusitanians)"],
		association: "Federação Portuguesa de Futebol (FPF)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/6/64/Portuguese_Football_Federation_logo.svg/500px-Portuguese_Football_Federation_logo.svg.png",
		no_wc_past_appearances: 8,
		wc_best_result: "Third plave (1966)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Quarter-finals"
	},
	{
		id: 44,
		name: "Uzbekistan",
		group: "K",
		flag_icon: "fi fi-uz",
		coach: "Fabio Cannavaro",
		coach_nationality: "fi fi-it",
		fifa_code: "UZB",
		are_hosts: "No",
		confederation: "AFC",
		nicknames: ["White Wolves", "Turanians"],
		association: "Uzbekistan Football Association (UFA)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Uzbekistan_Football_Association_logo.png/500px-Uzbekistan_Football_Association_logo.png",
		no_wc_past_appearances: 0,
	},
	{
		id: 45,
		name: "Croatia",
		group: "L",
		flag_icon: "fi fi-hr",
		coach: "Zlatko Dalić",
		fifa_code: "CRO",
		are_hosts: "No",
		confederation: "UEFA",
		fifa_ranking: 11,
		nicknames: ["Vatreni (Blazers)", "Kockasti (Chequered Ones)"],
		association: "Hrvatski nogometni savez (HNS)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/8/84/Croatian_Football_Federation_logo.svg/330px-Croatian_Football_Federation_logo.svg.png",
		no_wc_past_appearances: 6,
		wc_best_result: "Runners-up (2018)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Third place"
	},
	{
		id: 46,
		name: "England",
		group: "L",
		flag_icon: "fi fi-gb-eng",
		coach: "Thomas Tuchel",
		coach_nationality: "fi fi-de",
		fifa_code: "ENG",
		are_hosts: "No",
		confederation: "UEFA",
		nicknames: "The Three Lions",
		fifa_ranking: 4,
		association: "The Football Association (The FA)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/8/8b/England_national_football_team_crest.svg/330px-England_national_football_team_crest.svg.png",
		no_wc_past_appearances: 16,
		wc_best_result: "Champions (1966)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Quarter-finals"
	},
	{
		id: 47,
		name: "Ghana",
		group: "L",
		flag_icon: "fi fi-gh",
		coach: "Carlos Queiroz",
		coach_nationality: "fi fi-pt",
		fifa_code: "GHA",
		are_hosts: "No",
		confederation: "CAF",
		nicknames: "The Black Stars",
		fifa_ranking: 74,
		association: "Ghana Football Association",
		assc_crest: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Ghana_Football_Association_logo.svg/330px-Ghana_Football_Association_logo.svg.png", 
		no_wc_past_appearances: 4,
		wc_best_result: "Quarter-finals (2010)",
		played_in_last_wc: "Yes",
		last_wc_perf: "Group stage"
	},
	{
		id: 48,
		name: "Panama",
		group: "L",
		flag_icon: "fi fi-pa",
		coach: "Thomas Christiansen",
		coach_nationality: "fi fi-es",
		fifa_code: "PAN",
		are_hosts: "No",
		confederation: "CONCACAF",
		nicknames: ["Los Canaleros (The Canal Men)", "La Marea Roja (The Red Tide)"],
		fifa_ranking: 33,
		association: "Federación Panameña de Fútbol (FEPAFUT)",
		assc_crest: "https://upload.wikimedia.org/wikipedia/en/thumb/e/ee/Panamanian_Football_Federation_logo_2024.svg/330px-Panamanian_Football_Federation_logo_2024.svg.png",
		no_wc_past_appearances: 1,
		wc_best_result: "Group stage (2018)",
		played_in_last_wc: "No",
		last_wc_app: "Russia 2018",
		previous_wc_perf: "Group stage"
	}
]